export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOAD_USER_REQUEST_TODO = 'LOAD_USER_REQUEST_TODO';
export const LOAD_USER_SUCCESS_TODO = 'LOAD_USER_SUCCESS_TODO';
export const LOAD_USER_FAIL_TODO = 'LOAD_USER_FAIL_TODO';

export const LOAD_USER_REQUEST_PROCESS = 'LOAD_USER_REQUEST_PROCESS';
export const LOAD_USER_SUCCESS_PROCESS = 'LOAD_USER_SUCCESS_PROCESS';
export const LOAD_USER_FAIL_PROCESS = 'LOAD_USER_FAIL_PROCESS';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_RESET = 'UPDATE_PROFILE_RESET';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_RESET = 'UPDATE_USER_RESET';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
